### ISSUE TITLE
Feature: Make separator configurable

### ISSUE THREAD

**Issue by MiguelLatorre** [ap/vim-buftabline#16]
With the current font in my uxrvt-unicode terminal the separator does not look good (it does in gvim. Reading the source code I stopped at this line:
	let lpad     = g:buftabline_separators ? nr2char(0x23B8) : ' '

I think it would be nice to allow some other character via some globar variable like:
g:buftabline_separator_character

**Comment by ap** [comment]
I know this will be disappointing: I’m not going to do that. You’re asking for something too specific. There are too many other hardcoded bits about the design of these tabs, some of which only work well with other hardcoded bits, and I don’t want to make them all separately configurable one by one over time whenever someone asks for another bit; the result would be a mess.

It *would* be nice if people could make their own designs. I’ll try to think of how to abstract out the design in such a way that the result makes sense.

(This overlaps greatly with #13.)

**Comment by MiguelLatorre** [comment]
Ok. I see your point.
I think the request is firmly related (coupled) to the _buftabline_separators_, that's why I asked.

Hardcoding stuff is a bad design principle, so I agree about making a design change.

Thanks.
