### ISSUE TITLE
Skip buffer when its already open in another split.

### ISSUE THREAD

**Issue by neilpeter08** [ap/vim-buftabline#28]
Is there a way to do this?

**Comment by ap** [comment]
You mean instead of highlighting it?

**Comment by neilpeter08** [comment]
ahh sorry, I wanted `:bnext` to behave in a way where if the buffer is already open in another pane, it will skip that buffer then go to the next one. Then I realized that this plugin does not handle those kind of things sorry for asking.

**Comment by ap** [comment]
Ah. Yes, that’s outside the purview of this plugin. And no biggie.

This is actually something I wanted myself, though. So I wrote myself [a small plugin that does just that](https://github.com/ap/dotvim/blob/master/plugin/bufwm.vim). I’d like to release that if I ever figure out a proper shape for it, but I haven’t found that so far. What’s there works for me, though, and maybe it can be a starting point for you.

**Comment by neilpeter08** [comment]
This is exactly what I was looking for! Thanks @ap!!!
