### ISSUE TITLE
Feature Request: Highlight group for modified glyph/icon

### ISSUE THREAD

**Issue by asilvadesigns** [ap/vim-buftabline#29]
First off great plugin, really enjoying using it. Would love the ability to custom color the modified glyph, by default is `+`. Perhaps like this
```
hi BufTabLineModified guibg=XXXXXX guifg=XXXXXX etc...
```

**Comment by ap** [comment]
Hi, sorry it took me so long to even respond. I’m not sure I follow?

**Comment by asilvadesigns** [comment]
Hey, no problem. I'm referring to the modified flag that appears to the left of a buffer, I was wondering if there was a way to color that? I hope that makes sense.

**Comment by ap** [comment]
D’uh. Sorry for being slow. It’s an obvious request (now that I managed to figure it out…), so I agree the plugin should have a way of doing that. I’ll put that on my plate for this module.

(Not yet sure how exactly I want to do that. I’ve been meaning to make it easier to customise the plugin’s rendering more extensively, and it’s possible that this feature will be ugly to implement without that one, in which case it might be a while before it happens.)

**Comment by ap** [comment]
Following further discussion in #62 I’ll be adding ModifiedCurrent/ModifiedActive/ModifiedHidden highlight groups which correspond to the Current/Active/Hidden groups (except they’re applied to modified buffers, obviously). Airline does something very similar in its tabline plugin:

https://github.com/vim-airline/vim-airline/blob/a0298263b7fd55827839862ffd3a8d5b2a787a5c/autoload/airline/extensions/tabline.vim#L184-L202

By default the new highlight groups will be linked to their non-Modified counterpart so existing colorschemes and configurations will be unaffected. Basically the feature will be available but invisible at least initially. I don’t know where I’d find another three highlight groups to link to by default anyway… I think it will have to be left to colorschemes with explicit Buftabline support.

**Comment by noomly** [comment]
Is there any plan to implement this? Looks like #62 never went anywhere.

**Comment by ap** [comment]
Share and enjoy. 🙂
