### ISSUE TITLE
Give user a chance to change tabline option

### ISSUE THREAD

**Issue by tracyone** [ap/vim-buftabline#34]
here is my setting of your plugin:

```vim
    set showtabline=1  
    let g:buftabline_numbers=2
    let g:buftabline_show=1
    let g:buftabline_indicators=1
```

I have noticed that `tabline` option is empty when tab is opened.

This will cause visual differences in mccvim and gvim .

<img width="827" alt="2017-07-15 8 39 14" src="https://user-images.githubusercontent.com/4246425/28235022-29496bf0-6939-11e7-82a4-d6454f4f9b87.png">

<img width="827" alt="2017-07-15 8 39 23" src="https://user-images.githubusercontent.com/4246425/28235026-32b01298-6939-11e7-9909-3329d4a65e7e.png">

**Comment by ap** [comment]
I think #22 would cover this case, wouldn’t it?
