### ISSUE TITLE
Remove underline

### ISSUE THREAD

**Issue by luytsm** [ap/vim-buftabline#37]
How do i remove the underline off the buffernames like shown in your preview screenshot?

**Comment by ap** [comment]
I didn’t remove any underlines from anything? I am guessing the answer to your question is “use a another colorscheme” or `:help buftabline-colors`…

**Comment by luytsm** [comment]
I mean this

![screenshot from 2017-10-05 09-05-36](https://user-images.githubusercontent.com/7230854/31214630-52ec068a-a9ac-11e7-8749-f9f96014b6bb.png)
vs
![img](https://camo.githubusercontent.com/3ae8a69591bc00bbbe8a0944edff7f3b92a2f134/687474703a2f2f61702e6769746875622e696f2f76696d2d6275667461626c696e652f73637265656e73686f742e706e67)

This is in my vimrc. Using latest vim on Arch Linux

```
colorscheme default
set background=dark
```

I could've guessed it that it was a possible colorscheme issue. Is it possible to add this colorscheme setting?

**Comment by ap** [comment]
You can already override it. The documentation explains how.
