### ISSUE TITLE
Support lightline.vim

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ap/vim-buftabline#43]
I've already posted about this over there (itchyny/lightline.vim#264), but I thought I'd drop a note here, as well:

Lightline.vim includes a beautiful tabline replacement, but it only shows the classic vim tabpages. I'd love to see some integration, if possible!

**Comment by ap** [comment]
How would that look…?

There is of course already #22 about buftabline supporting Vim tab pages directly…
