### ISSUE TITLE
Plug mapping to go to the last buffer

### ISSUE THREAD

**Issue by ap** [ap/vim-buftabline#45]
@simaoneves [wrote](https://github.com/ap/vim-buftabline/commit/680471738fe1fcaab95d64f00004fb7d41a7d43a#commitcomment-25895562):

> Would love to see a mapping for something like Chromes last tab. So in a mac `Cmd-<number>` takes you to the desired tab, like buftabline, but if you have more than 9 tabs open and press `Cmd-9` it takes you to the last tab.
>
> Does anyone else uses this?

**Comment by simaoneves** [comment]
That's awesome! Thanks for opening this.
Well it sound great to me because i think i would use it, i don't know if other people work this way 👍  😄

**Comment by ap** [comment]
I dithered for a long time over the details of how to put this in. Make it conditional so it won’t be defined if the user sets `plug_max` to 0, or keep it unconditional? Leave the copypaste or try to abstract it, and how? Then I just got another PR that had me looking at this bit of code and that jogged something loose… so I’ve finally added this as a feature.

Share and enjoy. 😊
