### ISSUE TITLE
Ability to reorder buffer icons

### ISSUE THREAD

**Issue by ethantkoenig** [ap/vim-buftabline#48]
It would be very helpful if the buffer icons in the tabline could be reordered. Commands for moving the current buffer's icon to the left or right would be quite useful.

I understand that buffer icons are currently ordered by buffer numbers, which are assigned by vim and cannot be changed, but I would assume that it is possible to display the buffer icons in a different order.

p.s. thanks for making a slick plugin!

**Comment by ethantkoenig** [comment]
It just occurred to me that if the buffer icons were reordered, `:bp` and `:bn` would not behave as expected (since they would still follow the buffer-number ordering). So this feature would only make sense if buftabline offered alternate commands which followed the order in which buffer icons were displayed.

**Comment by ap** [comment]
… which is a whole big ball of wax. It also means the user has to buy in to this plugin in a much bigger way than just “drop this into your plugins and it works”. Worse, such plugins are more exclusionary: several plugins which all have some sort of reorderable buffer list almost certainly won’t cooperate, so you’d have to decide which of them is going to your “your” buffer list plugin.

So you can see, I hope, why I am reluctant to take this on board… even though it was one of the very first feature requests I got: #8

**Comment by ap** [comment]
(And sorry it took me so long to get back to you. After your “oh I see” I didn’t really have much to add, so I didn’t reply immediately, and then it got buried. I should have done better.)
