### ISSUE TITLE
Insert <C-u> into noremap definition to avoid E:481 No range allowed

### ISSUE THREAD

**Issue by foooomio** [ap/vim-buftabline#50]
`E:481 No range allowed` occurs when key mappings like `noremap <Leader>1 <Plug>BufTabLine.Go(1)` are defined and typing `1<Leader>1` by mistake. To avoid this, simply insert `<C-u>` into the noremap definition after `:`.

https://github.com/ap/vim-buftabline/blob/12f29d2cb11d79c6ef1140a0af527e9231c98f69/plugin/buftabline.vim#L177

For more information, see `:help N:` and https://vi.stackexchange.com/questions/9751/understanding-ctrl-u-combination :)

**Comment by ap** [comment]
Makes sense. Thank you for the pointer.
