### ISSUE TITLE
Feature request: ordinal _and_ buffer number in tab

### ISSUE THREAD

**Issue by deathlyfrantic** [ap/vim-buftabline#52]
Lately I'm finding myself using buffer numbers in various `:b` commands, but I still like ordinal numbering for switching between buffers using Buftabline. Would you be open to a `g:buftabline_numbers` option that shows both?

I'm thinking it would look something like: `1 foo.txt [1] | 2 bar.txt [7] | 3 baz.txt [2]`. If you're open to this I'd be glad to try implementing it myself, but I wanted to ask first since it could be treading on the ground of #35.

**Comment by ap** [comment]
I’m not opposed to this on general principle, but I don’t want the code to get too much more complex, and it would have to look nice in every possible combination of options. That seems… unlikely to be achievable. I’m not happy to discourage you (or that I’m turning away users while dragging my feet on a solution for such a long time), but I don’t want to compromise either…

**Comment by deathlyfrantic** [comment]
Continued in #35
