### ISSUE TITLE
Only one character is shown

### ISSUE THREAD

**Issue by parmort** [ap/vim-buftabline#57]
Hi, awesome plugin!

I've noticed that the listed tabs only have the last character in the filename listed ('c' for vimrc; 'm' for autoload.vim). This only seems to happen in Tmux right when I open vim. If I source my vimrc, then it solves the issue for that instance only. Works fine when not in Tmux, however. Not a big deal, just a minor inconvenience.

**Comment by ap** [comment]
Thanks, glad you enjoy it 😊 I’m not sure I follow… can you attach a screenshot or two?

**Comment by parmort** [comment]
I don't honestly know what happened. It's all fine now. Just had to restart my computer. I'll close it.

**Comment by ap** [comment]
That’s… weird. I wonder if that just means there’s still a bug lurking somewhere – though who knows even whose bug it would be…  Oh well.
