### ISSUE TITLE
Question regarding global manul installation

### ISSUE THREAD

**Issue by buttjake** [ap/vim-buftabline#63]
I'm making my own custom neovim package and and I'm trying to install this globally.
It should be as simple as putting "https://raw.githubusercontent.com/ap/vim-buftabline/master/plugin/buftabline.vim" in usr/share/nvim/runtime/autoload/ right ? Because I can't seem to get it to work.
It works without problems when I use something like vim-plug.

**Comment by ap** [comment]
No. You are putting `plugin/buftabline.vim` in `autoload/buftabline.vim`. Scripts in `<runtimedir>/plugin/` are always sourced on startup. Scripts in `<runtimedir>/autoload/` only get sourced when any of their functions are called from another script.
