### ISSUE TITLE
NeoVim external GUI tabline needs to be disabled separately

### ISSUE THREAD

**Issue by aj3423** [ap/vim-buftabline#65]
I'm using the latest nvim 0.4 + windows10(64bit). 
This is the result when opened two buffers with:

    :badd aaa
    :badd bbb

![image](https://user-images.githubusercontent.com/4710875/52896902-e420e900-3208-11e9-8a01-36e4e9afe149.png)

My config in vimrc:

    Plug 'ap/vim-buftabline'
    let g:buftabline_show=1
    let g:buftabline_numbers=2
    let g:buftabline_indicators='on'

Why there is a tabline, not buffer line ? How to make it same as in the demo screenshot?  Thanks.

**Comment by aj3423** [comment]
Found the solution:

    :Guitabline 0

**Comment by ap** [comment]
Thanks for tracking that down! I’m not a NeoVim user so it could have taken me a while. I’m reopening this because the plugin ought to take care of this automatically, much as it already does for GVim’s GUI tabs.

**Comment by bthodla** [comment]
> Found the solution:
> 
> ```
> :Guitabline 0
> ```

Thanks for taking the time out to figure this out. 

However, it didn't work for me. I get an error saying that it is not an editor command.

**Comment by oxysoft** [comment]
@bthodla It is `GuiTabline 0` in `ginit.vim`
