### ISSUE TITLE
Splits: non-focused split more highlighted than focused one

### ISSUE THREAD

**Issue by pabuisson** [ap/vim-buftabline#66]
Hey guys,

I've been finding this very disturbing for quite a while. I often work with splits and multiple buffers. In that kind of situations, the higlighting is very unintuitive: the inactive split buffers are much more emphasized (buffer name has a background color) than the active one (buffer name font color is set).

For instance : 

![capture d ecran 2019-02-22 a 11 49 41](https://user-images.githubusercontent.com/769918/53237910-224e5a80-3698-11e9-87a4-9e595be91e35.png)

What would be the best way to deal with this? Change the class used for highlighting? Make it a parameter? Any other idea?

**Comment by ap** [comment]
Does `:help buftabline-colors` leave you with further questions? 🙂

**Comment by pabuisson** [comment]
Hum. I'll have to try again, I did try to overwrite the colors and it did
not seem to work as I was expecting.

I'll give it another shot, this is not something I'm used to, I may have
done it wrong.

**Comment by pabuisson** [comment]
Okay I figured it out. Thanks for pointing me in the right direction @ap, I was almost there but messed up in my initial attempt to redefine the color groups. In case anyone is interested, I ended up with something like this : 

`hi link BufTabLineActive BufTabLineHidden`

so that visible but inactive buffers are highlighted just like any other hidden buffer. Only the focused buffer is now highlighted differently.

**Comment by ap** [comment]
Ah, yeah, that makes sense for just removing the distinction altogether.

Glad you’re all set. 🙂
