### ISSUE TITLE
Highlight name only of the buffer with cursor in it?

### ISSUE THREAD

**Issue by engeljh** [ap/vim-buftabline#68]
Right now if two buffers are open in a split, both names are highlighted in the tabline, no matter which buffer the cursor is in.  Can there be an option to highlight the name of only the one with the cursor?

**Comment by ap** [comment]
Sure, and there already is: [<tt>:help buftabline-colors</tt>](/ap/vim-buftabline/blob/14d208b1fa5f4308383e3ce429d57c84423029f9/doc/buftabline.txt#L107-L128)

Can you take it from there or do you need additional assistance?

**Comment by engeljh** [comment]
Yes, sorry.  I should have done a little more research before asking.

**Comment by ap** [comment]
No worries 🙂 Glad you like the plugin, share and enjoy.
