### ISSUE TITLE
tab highlight color override bug — coloring over underline

### ISSUE THREAD

**Issue by simonalford42** [ap/vim-buftabline#69]
I wanted to change the tab colors so that the current tab is highlighted brighter:
`highlight BufTabLineCurrent cterm=NONE ctermbg=15 ctermfg=8 gui=NONE guibg=#ffffff guifg=#d70000`

doing so made the underline of the current tab appear to be colored over:

![tag_view](https://user-images.githubusercontent.com/9351210/59461670-e75f6680-8def-11e9-9d15-50071d8f9e91.png)

Obviously not the most important bug in the world but I thought I would bring it to your attention.

**Comment by ap** [comment]
Hi. I’m… not sure what I’m looking for in that screenshot?

**Comment by simonalford42** [comment]
Here's a screenshot of what it originally looked like:

vimrc, the current tab, is normally underlined. When I change the current tab highlight color, the underline goes away.

![Screen Shot 2019-06-14 at 8 14 25 AM](https://user-images.githubusercontent.com/9351210/59508595-8893fe80-8e7c-11e9-8dcb-670e73fbe377.png)

**Comment by ap** [comment]
But you specified `NONE` for the `gui` attribute instead of `underline`… are you saying it should somehow put an underline there in spite of your configuration to the contrary…?

**Comment by simonalford42** [comment]
Ah I see thank you. Had copied the code from SO and didn't really know what it meant.
