### ISSUE TITLE
Is there a way not have gap between buftabline and window top?

### ISSUE THREAD

**Issue by zdmgmail** [ap/vim-buftabline#79]
![11-22_18:00:58](https://user-images.githubusercontent.com/50515839/99900800-d73dfd00-2cec-11eb-9062-58e536db8096.png)

hope not have gap between the window top and the white buftabline

**Comment by ap** [comment]
Maybe, but it’s not anything that Buftabline can control. I’m guessing that screenshot is Vim in some kind of terminal? Buftabline just renders the tabline, which Vim displays wherever it displays it. Vim in turn displays the tabline as the first line in the UI, which the terminal displays wherever it displays it. If the terminal imposes padding around the contents of the window, there is no way for Vim to circumvent that. If this screenshot is showing some kind of GUI version of Vim (or NeoVim?), that Vim GUI may have settings to control that padding specifically, and maybe you can use those to get it to look like you want.
