### ISSUE TITLE
Buffers with "%" in filename

### ISSUE THREAD

**Issue by syedelec** [ap/vim-buftabline#80]
Hi

Thanks for this plugin, I have an issue with buffers that have character "%" in filename:
example 1:
![image](https://user-images.githubusercontent.com/9877335/101110564-1c381e00-358e-11eb-988c-32f120e45ee2.png)
example 2:
![image](https://user-images.githubusercontent.com/9877335/101110616-38d45600-358e-11eb-8309-d210aba8e77b.png)

Instead of having "%" in the filename, I can see some random characters. The real filename is in the status bar.
Using neovim-nightly.

```
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Do you happen to know where it may come from ?

**Comment by ap** [comment]
Thanks for reporting the bug. Share and enjoy 🙂
