### ISSUE TITLE
Fork permission

### ISSUE THREAD

**Issue by awelormro** [ap/vim-buftabline#86]
Hello, I really adore this plugin, but I want to know if I can fork this plugin to add some features, like the option to enable or disable the filetype icon, customize the borders an another stuff

**Comment by YohananDiamond** [comment]
I believe so, as [the license is MIT](https://github.com/ap/vim-buftabline/blob/master/LICENSE).

**Comment by ap** [comment]
Correct. Feel free to do whatever you want.

Sorry I never answered before.
